#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop verisure.service >/dev/null
  systemctl disable verisure.service || true
  rm /var/log/thingsplex/verisure/* || true
fi